version: "3"
services:
   
  web:
    #container_name: web-app
    build: 
      dockerfile: Dockerfile
      context: E_shop
    ports:
      - "8005"
    environment:
      ConnectionStrings__RegisterConnectionString: "Server=db;Database=AuthBD;User=sa;Password=@Aa123456;Trusted_Connection=False;TrustServerCertificate=True;MultiSubnetFailover=True;Encrypt=false;"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "85:80"
   
  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/mssql/server:2017-CU4-ubuntu-16.04" #"microsoft/mssql-server-linux"
    expose:
      - "1433"
    environment:
      - SA_PASSWORD=@Aa123456
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"