version: "3.4"
services:
   
  web:
    #container_name: web-app
    build: 
      dockerfile: Dockerfile
      context: E_shop
    ports:
      - "8005:80"
    environment:
       ConnectionStrings__RegisterConnectionString: "Server=db;Initial Catalog=AuthDB;User ID=SA;Password=@Aa123456;Trusted_Connection=False;TrustServerCertificate=Yes;"
       ASPNETCORE_ENVIRONMENT: "Development"
       MSSQL_SA_PASSWORD: "@Aa123456"
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "85:80"
   
  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04" #"microsoft/mssql-server-linux"
    expose:
      - "1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_ENABLE_HADR: "1"
      MSSQL_AGENT_ENABLED: "1"
      MSSQL_SA_PASSWORD: "@Aa123456"
      MSSQL_PID: Express
    ports:
      - "1433:1433"