apiVersion: apps/v1 
kind: Deployment
metadata:
  name: esho-mssql-deployment
spec:
  selector:
    matchLabels:
      app: eshop-mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: eshop-mssql
      # image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
      # image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
        image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
      # image: microsoft/mssql-server-linux
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Sushant@123"
---

#Backend service
apiVersion: v1
kind: Service
metadata:
  name: eshop-mssql-service
spec:
  selector:
    app: eshop-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30201
  type: NodePort