#Frontend deployment 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eshop-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: sushantjadhavhcl/eshop-cicd:7
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings_RegisterConnectionString
            value: Server=eshop-mssql-service;Database=AuthDB;User=sa;Password="Sushant@123;Trusted_Connection=True;TrustServerCertificate=Yes;
        resources:
        limits:
           cpu: "2"
           memory: "2Gi"
           requests:
             cpu: "1"
---

#Frontend Service
kind: Service
apiVersion: v1
metadata:
  name: eshop-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30050
  type: NodePort


