#Frontend deployment 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eshop-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: sushantjadhavhcl/eshop-cicd:202404022819282828282828232222212113090906061816
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__RegisterConnectionString
            value: Server=eshop-mssql-service;Initial Catalog=AuthDB2;User ID=SA;Password=@Aa123456;Trusted_Connection=False;TrustServerCertificate=Yes;
        # resources:
        # limits:
        #    cpu: "3"
        #    memory: "5Gi"
        #    requests:
        #      cpu: "1"
---

#Frontend Service
kind: Service
apiVersion: v1
metadata:
  name: eshop-service
spec:
  selector:
    app: mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30052
  type: NodePort


