name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image and Updatating the deployment files
      run: |
           git config user.email "sushantjadhav416@gmail.com"
           git config user.name "sushantjadhav416"
           TAG_DATE=$(date +'%Y%m%d');
           docker build -t sushantjadhavhcl/eshop_updated:${TAG_DATE} ./E_shop/
           docker push sushantjadhavhcl/eshop_updated:${TAG_DATE}
           sed -i "s/replaceImageTag/${TAG_DATE}/g" E_shop/Deploymentfiles/Frontend.yaml
           git add -A
           git commit -m "Update deployment image to version ${TAG_DATE}
           git push https://${{ secrets.GI_TOKEN }}@github.com/sushantjadhav416/E-shop_project HEAD:master
           
    
