name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd E_shop
        docker build . --file Dockerfile --tag eshop-updated:$(date +%s)
        docker push sushantjadhavhcl/eshop-updated:$(date +%s)
